name: Download & Release on Tag
on:
  push:
    tags:
      - '*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download static FFmpeg
        run: |
          mkdir /tmp/3dparty-bins
          wget "https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz"
          wget "https://github.com/RustedBytes/nnnoiseless-releases/releases/download/v0.1.0/nnnoiseless"
          tar xf ffmpeg-git-amd64-static.tar.xz
          mv nnnoiseless /tmp/3dparty-bins
          mv ffmpeg-git-*-amd64-static/ /tmp/ffmpeg
          mv /tmp/ffmpeg/ffmpeg /tmp/3dparty-bins/
          mv /tmp/ffmpeg/ffprobe /tmp/3dparty-bins/
          chmod +x /tmp/3dparty-bins/*
      - name: Download wav-files-trim
        run: wget -O "/tmp/wav-files-trim" "https://github.com/RustedBytes/wav-files-trim/releases/download/v0.1.0/wav-files-trim"
      - name: Download wav-files-filter
        run: wget -O "/tmp/wav-files-filter" "https://github.com/RustedBytes/wav-files-filter/releases/download/v0.1.1/wav-files-filter"
      - name: Download wav-files-stats
        run: wget -O "/tmp/wav-files-stats" "https://github.com/RustedBytes/wav-files-stats/releases/download/v0.1.1/wav-files-stats"
      - name: Download wav-files-ss
        run: wget -O "/tmp/wav-files-ss" "https://github.com/RustedBytes/wav-files-ss/releases/download/v0.1.1/wav-files-ss"
      - name: Download wav-files-concat
        run: wget -O "/tmp/wav-files-concat" "https://github.com/RustedBytes/wav-files-concat/releases/download/v0.1.1/wav-files-concat"
      - name: Download wav-files-chunker
        run: wget -O "/tmp/wav-files-chunker" "https://github.com/RustedBytes/wav-files-chunker/releases/download/v0.1.1/wav-files-chunker"
      - name: Download wav-files-validate
        run: wget -O "/tmp/wav-files-validate" "https://github.com/RustedBytes/wav-files-validate/releases/download/v0.1.0/wav-files-validate"
      - name: Download wav-files-spectrogram
        run: wget -O "/tmp/wav-files-spectrogram" "https://github.com/RustedBytes/wav-files-spectrogram/releases/download/v0.1.0/wav-files-spectrogram"
      - name: Download wav-files-normalize
        run: wget -O "/tmp/wav-files-normalize" "https://github.com/RustedBytes/wav-files-normalize/releases/download/v0.1.0/wav-files-normalize"
      - name: Download wav-files-format
        run: wget -O "/tmp/wav-files-format" "https://github.com/RustedBytes/wav-files-format/releases/download/v0.1.0/wav-files-format"
      - name: Download wav-files-augment
        run: wget -O "/tmp/wav-files-augment" "https://github.com/RustedBytes/wav-files-augment/releases/download/v0.1.0/wav-files-augment"
      - name: Download wav-files-convert
        run: wget -O "/tmp/wav-files-convert" "https://github.com/RustedBytes/wav-files-convert/releases/download/v0.1.0/wav-files-convert"
      - name: Download wav-files-denoise
        run: wget -O "/tmp/wav-files-denoise" "https://github.com/RustedBytes/wav-files-denoise/releases/download/v0.1.0/wav-files-denoise"
      - name: Make files executable
        run: chmod +x /tmp/wav-files-*
      - name: Strip files
        run: strip -s /tmp/wav-files-*
      - name: Create ZIP archive
        run: zip -j /tmp/wav-files-toolkit.zip /tmp/wav-files-*
      - name: Create ZIP archive with additional binaries
        run: zip -j /tmp/3d-party-bins.zip /tmp/3dparty-bins/*
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /tmp/3d-party-bins.zip
            /tmp/wav-files-toolkit.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
