name: Download & Release on Tag
on:
  push:
    tags:
      - '*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download wav-files-filter
        run: wget -O "/tmp/wav-files-filter" "https://github.com/RustedBytes/wav-files-filter/releases/download/v0.1.0/wav-files-filter"
      - name: Download wav-files-stats
        run: wget -O "/tmp/wav-files-stats" "https://github.com/RustedBytes/wav-files-stats/releases/download/v0.1.0/wav-files-stats"
      - name: Download wav-files-ss
        run: wget -O "/tmp/wav-files-ss" "https://github.com/RustedBytes/wav-files-ss/releases/download/v0.1.0/wav-files-ss"
      - name: Download wav-files-concat
        run: wget -O "/tmp/wav-files-concat" "https://github.com/RustedBytes/wav-files-concat/releases/download/v0.1.0/wav-files-concat"
      - name: Download wav-files-chunker
        run: wget -O "/tmp/wav-files-chunker" "https://github.com/RustedBytes/wav-files-chunker/releases/download/v0.1.0/wav-files-chunker"
      
      - name: Create ZIP archive
        run: zip -j /tmp/wav-files-toolkit.zip /tmp/wav-files-*
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/wav-files-toolkit.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
