name: build
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download static FFmpeg
        run: |
          mkdir /tmp/3dparty-bins
          wget "https://github.com/RustedBytes/audio-from-video/releases/download/v0.2.2/audio-from-video"
          mv audio-from-video /tmp/3dparty-bins/audio-from-video
          wget "https://github.com/RustedBytes/data-viewer-audio/releases/download/v0.2.2/data-viewer-audio"
          mv data-viewer-audio /tmp/3dparty-bins/data-viewer-audio
          wget "https://github.com/RustedBytes/audio-parquet-merger/releases/download/v0.1.0/audio-parquet-merger"
          mv audio-parquet-merger /tmp/3dparty-bins/audio-parquet-merger
          wget "https://github.com/hangxie/parquet-tools/releases/download/v1.37.1/parquet-tools-v1.37.1-linux-amd64.gz"
          gzip -d parquet-tools-v1.37.1-linux-amd64.gz
          mv parquet-tools-v1.37.1-linux-amd64 /tmp/3dparty-bins/parquet-tools
          wget "https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz"
          wget "https://github.com/RustedBytes/nnnoiseless-releases/releases/download/v0.1.0/nnnoiseless"
          tar xf ffmpeg-git-amd64-static.tar.xz
          mv nnnoiseless /tmp/3dparty-bins
          mv ffmpeg-git-*-amd64-static/ /tmp/ffmpeg
          mv /tmp/ffmpeg/ffmpeg /tmp/3dparty-bins/
          mv /tmp/ffmpeg/ffprobe /tmp/3dparty-bins/
          strip -s /tmp/3dparty-bins/*
          chmod +x /tmp/3dparty-bins/*
      - name: Download wav-files-trim
        run: wget -O "/tmp/wav-files-trim" "https://github.com/RustedBytes/wav-files-trim/releases/download/v0.1.0/wav-files-trim"
      - name: Download audios-to-dataset
        run: wget -O "/tmp/audios-to-dataset" "https://github.com/RustedBytes/audios-to-dataset/releases/download/v0.2.4/audios-to-dataset"
      - name: Download extract-audio
        run: wget -O "/tmp/extract-audio" "https://github.com/RustedBytes/extract-audio/releases/download/v0.2.6/extract-audio"
      - name: Download wav-files-filter
        run: wget -O "/tmp/wav-files-filter" "https://github.com/RustedBytes/wav-files-filter/releases/download/v0.2.0/wav-files-filter"
      - name: Download wav-files-stats
        run: wget -O "/tmp/wav-files-stats" "https://github.com/RustedBytes/wav-files-stats/releases/download/v0.2.1/wav-files-stats"
      - name: Download wav-files-ss
        run: wget -O "/tmp/wav-files-ss" "https://github.com/RustedBytes/wav-files-ss/releases/download/v0.1.1/wav-files-ss"
      - name: Download wav-files-concat
        run: wget -O "/tmp/wav-files-concat" "https://github.com/RustedBytes/wav-files-concat/releases/download/v0.1.1/wav-files-concat"
      - name: Download wav-files-chunker
        run: wget -O "/tmp/wav-files-chunker" "https://github.com/RustedBytes/wav-files-chunker/releases/download/v0.1.1/wav-files-chunker"
      - name: Download wav-files-validate
        run: wget -O "/tmp/wav-files-validate" "https://github.com/RustedBytes/wav-files-validate/releases/download/v0.1.0/wav-files-validate"
      - name: Download wav-files-spectrogram
        run: wget -O "/tmp/wav-files-spectrogram" "https://github.com/RustedBytes/wav-files-spectrogram/releases/download/v0.1.0/wav-files-spectrogram"
      - name: Download wav-files-normalize
        run: wget -O "/tmp/wav-files-normalize" "https://github.com/RustedBytes/wav-files-normalize/releases/download/v0.1.0/wav-files-normalize"
      - name: Download wav-files-format
        run: wget -O "/tmp/wav-files-format" "https://github.com/RustedBytes/wav-files-format/releases/download/v0.1.1/wav-files-format"
      - name: Download wav-files-augment
        run: wget -O "/tmp/wav-files-augment" "https://github.com/RustedBytes/wav-files-augment/releases/download/v0.1.0/wav-files-augment"
      - name: Download wav-files-convert
        run: wget -O "/tmp/wav-files-convert" "https://github.com/RustedBytes/wav-files-convert/releases/download/v0.1.0/wav-files-convert"
      - name: Download wav-files-denoise
        run: wget -O "/tmp/wav-files-denoise" "https://github.com/RustedBytes/wav-files-denoise/releases/download/v0.1.0/wav-files-denoise"
      - name: Download wav-files-denoise-api
        run: wget -O "/tmp/wav-files-denoise-api" "https://github.com/RustedBytes/wav-files-denoise-api/releases/download/v0.2.0/wav-files-denoise-api"
      - name: Download wav-files-vad
        run: wget -O "/tmp/wav-files-vad" "https://github.com/RustedBytes/wav-files-vad/releases/download/v0.2/wav-files-vad"
      - name: Download wav-files-vad-api
        run: wget -O "/tmp/wav-files-vad-api" "https://github.com/RustedBytes/wav-files-vad-api/releases/download/v0.1.1/wav-files-vad-api"
      - name: Download wav-files-tempo
        run: wget -O "/tmp/wav-files-tempo" "https://github.com/RustedBytes/wav-files-tempo/releases/download/v0.1.0/wav-files-tempo"
      - name: Download wav-files-echo
        run: wget -O "/tmp/wav-files-echo" "https://github.com/RustedBytes/wav-files-echo/releases/download/v0.1.0/wav-files-echo"
      - name: Download babylonify
        run: wget -O "/tmp/babylonify" "https://github.com/RustedBytes/babylonify/releases/download/v0.1.0/babylonify"
      - name: Make files executable
        run: |
          chmod +x /tmp/wav-files-*
          chmod +x /tmp/audios-to-dataset
          chmod +x /tmp/extract-audio
          chmod +x /tmp/babylonify
      - name: Strip files
        run: |
          strip -s /tmp/wav-files-*
          strip -s /tmp/audios-to-dataset
          strip -s /tmp/extract-audio
          strip -s /tmp/babylonify
      - name: Create ZIP archive - 1
        run: zip -j /tmp/additional-tools.zip /tmp/audios-to-dataset /tmp/extract-audio /tmp/babylonify
      - name: Create ZIP archive - 2
        run: zip -j /tmp/wav-files-toolkit.zip /tmp/wav-files-*
      - name: Create ZIP archive - 3
        run: zip -j /tmp/3rd-party-bins.zip /tmp/3dparty-bins/*
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /tmp/3rd-party-bins.zip
            /tmp/additional-tools.zip
            /tmp/wav-files-toolkit.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
